// Logout
export const LOGOUT_REQUESTING = 'LOGOUT_REQUESTING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'  
export const LOGOUT_ERROR = 'LOGOUT_ERROR' 

// Smartcar
export const SMARTCAR_AUTH_REQUESTING = 'SMARTCAR_AUTH_REQUESTING'
export const SMARTCAR_AUTH_SUCCESS = 'SMARTCAR_AUTH_SUCCESS'  
export const SMARTCAR_AUTH_ERROR = 'SMARTCAR_AUTH_ERROR' 
export const SMARTCAR_RESPONSE_SUCCESS = 'SMARTCAR_RESPONSE_SUCCESS'